In [1]:
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [25]:
data = pd.read_csv('Decision Tree/Decision Tree.csv', delimiter=',')
data[0:5]

JobNumber    MoEducate  MoAge MoBloodGroup  CityNumber   TypeDelivery  \
0  housewife  High school     19           B+           5  Vaginal birth   
1  housewife   illiterate     33           A+           5       Cesarean   
2  housewife  High school     24           B+           5  Vaginal birth   
3  housewife   elementary     35           B+           5  Vaginal birth   
4  housewife   illiterate     44           B+           5       Cesarean   

   NumberLiveBirth  NumberDeathNeonate  NumberAboration EthnicNumber  \
0                0                   1                0         Fars   
1                3                   1                2         Fars   
2                1                   1                0         Fars   
3                2                   1                3         Fars   
4                8                   1                0         Fars   

  familymarrige                Neonateweight           taneshlife  \
0            No  Between 2500 and Unknown000          Always calm   
1            No  Between 2500 and Unknown000  Sometimes stressful   
2            No  Between 2500 and Unknown000          Always calm   
3            No                      Unknown          Always calm   
4            No                      Unknown      Relatively calm   

   Paritypregnancy  Contraceptionbeforepregnancy Smokingduringpregnancy  \
0                1                             2                     No   
1                6                             2                     No   
2                2                             1                     No   
3                6                             1                     No   
4                9                             2                     No   

  Smokingparents Previousoutcomepregnanancy  
0             No                 StillBirth  
1             No                  LiveBirth  
2             No                  LiveBirth  
3             No                 StillBirth  
4             No                  LiveBirth

In [3]:
data.shape

(3339, 18)

### Pre-processing
Using data as the Copy (2).csv data read by pandas, declare the following variables:

  1. X as the Feature Matrix (data of data)
  2. y as the response vector (target)

Remove the column containing the target name since it doesn't contain numeric values.


In [4]:
X = data[['JobNumber', 'MoEducate','MoAge', 'MoBloodGroup', 'CityNumber', 'TypeDelivery', 'NumberLiveBirth','NumberDeathNeonate', 'NumberAboration', 'EthnicNumber', 'familymarrige', 'Neonateweight', 'taneshlife', 'Paritypregnancy', 'Contraceptionbeforepregnancy', 'Smokingduringpregnancy', 'Smokingparents']] .values  #.astype(float)
X[0:5]

array([[ 1,  4, 19,  3,  5,  1,  0,  1,  0,  1,  2,  2,  1,  1,  2,  2,
         2],
       [ 1,  1, 33,  1,  5,  2,  3,  1,  2,  1,  2,  2,  3,  6,  2,  2,
         2],
       [ 1,  4, 24,  3,  5,  1,  1,  1,  0,  1,  2,  2,  1,  2,  1,  2,
         2],
       [ 1,  2, 35,  3,  5,  1,  2,  1,  3,  1,  2,  4,  1,  6,  1,  2,
         2],
       [ 1,  1, 44,  3,  5,  2,  8,  1,  0,  1,  2,  4,  2,  9,  2,  2,
         2]], dtype=int64)

In [5]:
y = data['Previousoutcomepregnanancy'].values
y[0:5]

array([4, 1, 1, 3, 1], dtype=int64)

### Setting up the Decision Tree
We will be using train/test split on our decision tree. Let's import train_test_split from sklearn.cross_validation.


In [7]:
from sklearn.model_selection import train_test_split


Now train_test_split will return 4 different parameters. We will name them:
X_trainset, X_testset, y_trainset, y_testset

The train_test_split will need the parameters:
X, y, test_size=0.3, and random_state=3.

The X and y are the arrays required before the split, the test_size represents the ratio of the testing dataset, and the random_state ensures that we obtain the same splits

In [8]:
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.3, random_state=3)


#### Modeling
 We will first create an instance of the DecisionTreeClassifier called drugTree.
 Inside of the classifier, specify criterion="entropy" so we can see the information gain of each node.

In [9]:
PreviousoutcomepregnanancyTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
PreviousoutcomepregnanancyTree # it shows the default parameters

DecisionTreeClassifier(criterion='entropy', max_depth=4)

Next, we will fit the data with the training feature matrix X_trainset and training response vector y_trainset



In [10]:
PreviousoutcomepregnanancyTree.fit(X_trainset,y_trainset)


DecisionTreeClassifier(criterion='entropy', max_depth=4)

### Prediction
Let's make some predictions on the testing dataset and store it into a variable called predTree.



In [11]:
predTree = PreviousoutcomepregnanancyTree.predict(X_testset)


You can print out predTree and y_testset if you want to visually compare the predictions to the actual values.



In [12]:
print (predTree [0:5])
print (y_testset [0:5])

[1 1 4 1 1]
[1 1 4 1 1]


### Evaluation
 Next, let's import metrics from sklearn and check the accuracy of our model.


In [27]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree))

DecisionTrees's Accuracy:  0.9331337325349301


Accuracy classification score computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.

In multilabel classification, the function returns the subset accuracy. If the entire set of predicted labels for a sample strictly match with the true set of labels, then the subset accuracy is 1.0; otherwise it is 0.0.